---
- name: install apache in apps
  hosts: db
  become: true
  vars:
    mysql_databases:
      - name: webdb
        collation: utf8_general_ci
        encoding: utf8
        replicate: 1
    mysql_user_password: tiger
    mysql_root_password: tiger
  roles:
    - geerlingguy.mysql    
...